/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utils;

/**
 *
 * @author Manuel
 */
public class Mensajes {

    public static final String PETICION_LOGIN = "P1LOGIN";
    public final static String PETICION_REGISTRO = "P2REGISTRO";
    public final static String PETICION_MOSTRAR_RESTAURANTES = "P3MOSTRARRESTAURANTES";
    public final static String PETICION_EDITAR_PERFIL = "P4EDITARPERFIL";
    public final static String PETICION_OBTENER_RESTAURANTE = "P5OBTENERRESTAURANTE";
    public final static String PETICION_OBTENER_CATEGORIAS = "P6OBTENERCATEGORIAS";
    public final static String PETICION_MOSTRAR_VALORACIONES = "P7MOSRTARVALORACIONES";
    public final static String PETICION_ANADIR_VALORACION = "P8ANADIRVALORACION";
    public final static String PETICION_REALIZAR_PEDIDO = "P9REALIZARPEDIDO";
    public final static String PETICION_CARGAR_IMAGEN = "P10IMAGEN";
    public final static String PETICION_MOSTRAR_PEDIDOS_USUARIO = "P11LISTAPEDIDOS";
    public final static String PETICION_MOSTRAR_DETALLES_PEDIDO = "P12DETALLESPEDIDO";
    public final static String PETICION_LOGIN_REPARTIDOR = "P13LOGINREPARTIDOR";
    public final static String PETICION_REGISTRO_REPARTIDOR = "P14REGISTROREPARTIDOR";
    public final static String PETICION_EDITAR_PERFIL_REPARTIDOR = "P15EDITARPERFILREPARTIDOR";
    public final static String PETICION_MOSTRAR_PEDIDOS_REPARTIDOR = "P16PEDIDOSREPARTIDOR";
    public final static String PETICION_MOSTRAR_DETALLES_PEDIDO_REPARTIDOR = "P17DETALLESPEDIDOREPARTIDOR";
    public final static String PETICION_ACTUALIZAR_ESTADO = "P18ACTUALIZARESTADO";
    public final static String PETICION_OBTENER_ESTADOS = "P19OBTENERESTADOS";
    //  public final static String PETICION_CONTRASENA_OLVIDADA = "P20CONTRASENAOLVIDADA";
    public final static String PETICION_RECARGAR_UBICACION = "P20RECARGARUBICACION";
    public final static String PETICION_RESTAURANTE_REPARTIDOR = "P21RESTAURATEREPARTIDOR";
    public final static String PETICION_MOSTRAR_RESTAURANTE_ID = "P22MOSTRARRESTAURANTEID";
    public final static String PETICION_OBTENER_NUMERO_RESTAURANTES = "P23OBTENERNUMRESTAURANTES";

    //Correcto
    public static final String PETICION_LOGIN_CORRECTO = "C1LOGIN";
    public final static String PETICION_REGISTRO_CORRECTO = "C2REGISTRO";
    public final static String PETICION_MOSTRAR_RESTAURANTES_CORRECTO = "C3MOSTRARRESTAURANTES";
    public final static String PETICION_EDITAR_PERFIL_CORRECTO = "C4EDITARPERFIL";
    public final static String PETICION_OBTENER_RESTAURANTE_CORRECTO = "C5OBTENERRESTAURANTE";
    public final static String PETICION_OBTENER_CATEGORIAS_CORRECTO = "C6OBTENERCATEGORIAS";
    public final static String PETICION_MOSTRAR_VALORACIONES_CORRECTO = "C7MOSRTARVALORACIONES";
    public final static String PETICION_ANADIR_VALORACION_CORRECTO = "C8ANADIRVALORACION";
    public final static String PETICION_REALIZAR_PEDIDO_CORRECTO = "C9REALIZARPEDIDO";
    public final static String PETICION_MOSTRAR_PEDIDOS_USUARIO_CORRECTO = "C11LISTAPEDIDOS";
    public final static String PETICION_MOSTRAR_DETALLES_PEDIDO_CORRECTO = "C12DETALLESPEDIDO";
    public final static String PETICION_LOGIN_REPARTIDOR_CORRECTO = "C13LOGINREPARTIDOR";
    public final static String PETICION_REGISTRO_REPARTIDOR_CORRECTO = "C14REGISTROREPARTIDOR";
    public final static String PETICION_EDITAR_PERFIL_REPARTIDOR_CORRECTO = "C15EDITARPERFILREPARTIDOR";
    public final static String PETICION_MOSTRAR_PEDIDOS_REPARTIDOR_CORRECTO = "C16PEDIDOSREPARTIDOR";
    public final static String PETICION_MOSTRAR_DETALLES_PEDIDO_REPARTIDOR_CORRECTO = "C17DETALLESPEDIDOREPARTIDOR";
    public final static String PETICION_ACTUALIZAR_ESTADO_CORRECTO = "C18ACTUALIZARESTADO";
    public final static String PETICION_OBTENER_ESTADOS_CORRECTO = "C19OBTENERESTADOS";
    //public final static String PETICION_CONTRASENA_OLVIDADA_CORRECTO = "C20CONTRASENAOLVIDADA";
    public final static String PETICION_RECARGAR_UBICACION_CORRECTO = "C20RECARGARUBICACION";
    public final static String PETICION_RESTAURANTE_REPARTIDOR_CORRECTO = "C21RESTAURATEREPARTIDOR";
    public final static String PETICION_MOSTRAR_RESTAURANTE_ID_CORRECTO = "C22MOSTRARRESTAURANTEID";
    public final static String PETICION_OBTENER_NUMERO_RESTAURANTES_CORRECTO = "C23OBTENERNUMRESTAURANTES";

    //Error
    public static final String PETICION_LOGIN_ERROR = "E1LOGIN";
    public final static String PETICION_REGISTRO_ERROR = "E2REGISTRO";
    public final static String PETICION_MOSTRAR_RESTAURANTES_ERROR = "E3MOSTRARRESTAURANTES";
    public final static String PETICION_EDITAR_PERFIL_ERROR = "E4EDITARPERFIL";
    public final static String PETICION_OBTENER_RESTAURANTE_ERROR = "E5OBTENERRESTAURANTE";
    public final static String PETICION_OBTENER_CATEGORIAS_ERROR = "E6OBTENERCATEGORIAS";
    public final static String PETICION_MOSTRAR_VALORACIONES_ERROR = "E7MOSRTARVALORACIONES";
    public final static String PETICION_ANADIR_VALORACION_ERROR = "E8ANADIRVALORACION";
    public final static String PETICION_REALIZAR_PEDIDO_ERROR = "E9REALIZARPEDIDO";
    public final static String PETICION_MOSTRAR_PEDIDOS_USUARIO_ERROR = "E11LISTAPEDIDOS";
    public final static String PETICION_MOSTRAR_DETALLES_PEDIDO_ERROR = "P12DETALLESPEDIDO";
    public final static String PETICION_LOGIN_REPARTIDOR_ERROR = "E13LOGINREPARTIDOR";
    public final static String PETICION_REGISTRO_REPARTIDOR_ERROR = "E14REGISTROREPARTIDOR";
    public final static String PETICION_EDITAR_PERFIL_REPARTIDOR_ERROR = "E15EDITARPERFILREPARTIDOR";
    public final static String PETICION_MOSTRAR_PEDIDOS_REPARTIDOR_ERROR = "E16PEDIDOSREPARTIDOR";
    public final static String PETICION_MOSTRAR_DETALLES_PEDIDO_REPARTIDOR_ERROR = "E17DETALLESPEDIDOREPARTIDOR";
    public final static String PETICION_ACTUALIZAR_ESTADO_ERROR = "E18ACTUALIZARESTADO";
    public final static String PETICION_OBTENER_ESTADOS_ERROR = "E19OBTENERESTADOS";
    // public final static String PETICION_CONTRASENA_OLVIDADA_ERROR = "E20CONTRASENAOLVIDADA";
    public final static String PETICION_RECARGAR_UBICACION_ERROR = "E20RECARGARUBICACION";
    public final static String PETICION_RESTAURANTE_REPARTIDOR_ERROR = "E21RESTAURATEREPARTIDOR";
    public final static String PETICION_MOSTRAR_RESTAURANTE_ID_ERROR = "E22MOSTRARRESTAURANTEID";
    public final static String PETICION_OBTENER_NUMERO_RESTAURANTES_ERROR = "E23OBTENERNUMRESTAURANTES";

    //Restaurante
    public final static String PETICION_LOGIN_RESTAURANTE = "PR1LOGIN";
    public final static String PETICION_REGISTRO_RESTAURANTE = "PR2REGISTRO";
    public final static String PETICION_MODIFICAR_RESTAURANTE = "PR3MODIFICAR";
    public final static String PETICION_MOSTRAR_CARTA = "PR4CARTA";
    public final static String PETICION_ANADIR_PRODUCTO = "PR5ANADIRPRODUCTO";
    public final static String PETICION_MODIFICAR_PRODUCTO = "PR6MODIFICARPRODUCTO";
    public final static String PETICION_ELIMINAR_PRODUCTO = "PR7ELIMINARPRODUCTO";
    public final static String PETICION_MOSTRAR_PEDIDOS = "PR8MOSTRARPEDIDOS";
    public final static String PETICION_MOSTRAR_DETALLESPEDIDO = "PR9DETALLESPEDIDO";
    public final static String PETICION_ANADIR_REPARTIDOR = "PR10ANADIRREPARTIDOR";
    public final static String PETICION_MOSTRAR_REPARTIDORES = "PR11MOSTRARREPARTIDORES";
    public final static String PETICION_ELIMINAR_REPARTIDOR = "PR12ELIMINARREPARTIDOR";
    public final static String PETICION_FOTO_PRODUCTO = "PR13FOTOPRODUCTO";
    public final static String PETICION_ADJUDICAR_REPARTIDOR = "PR14ADJUDICARREPARTIDOR";
    public final static String PETICION_CAMBIAR_ESTADO = "PR15CAMBIARESTADO";

    //Correcto
    public final static String PETICION_LOGIN_RESTAURANTE_CORRECTO = "CR1LOGIN";
    public final static String PETICION_REGISTRO_RESTAURANTE_CORRECTO = "CR2REGISTRO";
    public final static String PETICION_MODIFICAR_RESTAURANTE_CORRECTO = "CR3MODIFICAR";
    public final static String PETICION_MOSTRAR_CARTA_CORRECTO = "CR4CARTA";
    public final static String PETICION_ANADIR_PRODUCTO_CORRECTO = "CR5ANADIRPRODUCTO";
    public final static String PETICION_MODIFICAR_PRODUCTO_CORRECTO = "CR6MODIFICARPRODUCTO";
    public final static String PETICION_ELIMINAR_PRODUCTO_CORRECTO = "CR7ELIMINARPRODUCTO";
    public final static String PETICION_MOSTRAR_PEDIDOS_CORRECTO = "CR8MOSTRARPEDIDOS";
    public final static String PETICION_MOSTRAR_DETALLESPEDIDO_CORRECTO = "CR9DETALLESPEDIDO";
    public final static String PETICION_ANADIR_REPARTIDOR_CORRECTO = "CR10ANADIRREPARTIDOR";
    public final static String PETICION_MOSTRAR_REPARTIDORES_CORRECTO = "CR11MOSTRARREPARTIDORES";
    public final static String PETICION_ELIMINAR_REPARTIDOR_CORRECTO = "CR12ELIMINARREPARTIDOR";
    public final static String PETICION_FOTO_PRODUCTO_CORRECTO = "CR13FOTOPRODUCTO";
    public final static String PETICION_ADJUDICAR_REPARTIDOR_CORRECTO = "CR14ADJUDICARREPARTIDOR";
    public final static String PETICION_CAMBIAR_ESTADO_CORRECTO = "CR15CAMBIARESTADO";

    //Error
    public final static String PETICION_LOGIN_RESTAURANTE_ERROR = "ER1LOGIN";
    public final static String PETICION_REGISTRO_RESTAURANTE_ERROR = "ER2REGISTRO";
    public final static String PETICION_MODIFICAR_RESTAURANTE_ERROR = "ER3MODIFICAR";
    public final static String PETICION_MOSTRAR_CARTA_ERROR = "ER4CARTA";
    public final static String PETICION_ANADIR_PRODUCTO_ERROR = "ER5ANADIRPRODUCTO";
    public final static String PETICION_MODIFICAR_PRODUCTO_ERROR = "ER6MODIFICARPRODUCTO";
    public final static String PETICION_ELIMINAR_PRODUCTO_ERROR = "ER7ELIMINARPRODUCTO";
    public final static String PETICION_MOSTRAR_PEDIDOS_ERROR = "ER8MOSTRARPEDIDOS";
    public final static String PETICION_MOSTRAR_DETALLESPEDIDO_ERROR = "ER9DETALLESPEDIDO";
    public final static String PETICION_ANADIR_REPARTIDOR_ERROR = "ER10ANADIRREPARTIDOR";
    public final static String PETICION_MOSTRAR_REPARTIDORES_ERROR = "ER11MOSTRARREPARTIDORES";
    public final static String PETICION_ELIMINAR_REPARTIDOR_ERROR = "ER12ELIMINARREPARTIDOR";
    public final static String PETICION_ADJUDICAR_REPARTIDOR_ERROR = "ER14ADJUDICARREPARTIDOR";
    public final static String PETICION_CAMBIAR_ESTADO_ERROR = "ER15CAMBIARESTADO";

}
